version: "3.8"
services:
  chat:
    container_name: chat
    image: chat
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    networks:
      - chat-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - chat_db
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max_old_space_size=2048
      - PORT=8080
      - DB_PORT=27017
      - DB_SSL=false
      - DB_HOST=chat_db
      - DB_NAME=chat
      - DB_USER=root
      - DB_PASS=root
      - DB_PARAMETERS=
      - GOOGLE_CLIENT_ID=472929644816-o8rsct2j16v1ect1to432q9nonk3h3l8.apps.googleusercontent.com
      - JWT_SECRET=123456
  chat_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - chat-network
    volumes:
      - mongodb_data_container:/data/db
networks:
  chat-network: null
volumes:
  db: null
  mongodb_data_container: null
